SELECT COUNT(EMPNO) FROM EMP;

SELECT * FROM EMP WHERE MGR IS NOT NULL;

SELECT SUM(SAL) FROM EMP WHERE SAL <= 2000;

SELECT COUNT(EMPNO), avg(SAL) FROM EMP WHERE  JOB ='MANAGER';

SELECT MIN(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP WHERE DEPTNO =30;

SELECT COUNT(DISTINCT JOB) FROM EMP;

SELECT * FROM 제품;
SELECT 제조업체, COUNT(제조업체) FROM 제품 -- GROUP BY 사용시 GROUP 할 속성 또는 집계함수
	group by 제조업체;
        
SELECT 등급, ROUND(avg(적립금),0) AS 평균적립금,COUNT(*) AS 고객수
	FROM 고객 
GROUP BY 등급 HAVING AVG(적립금)>=1000
ORDER BY AVG(적립금) DESC;

SELECT DEPTNO,COUNT(*) FROM EMP GROUP BY DEPTNO;

SELECT SUM(SAL),DEPTNO FROM EMP GROUP BY DEPTNO;

SELECT COUNT(*), DEPTNO, JOB FROM EMP GROUP BY DEPTNO,JOB;

CREATE TABLE NOODLE (
 NUM INT
 , NAME VARCHAR(50)
 , COMPANY VARCHAR(10)
 , KIND VARCHAR(1)
 , PRICE INT
 , E_DATE DATETIME
);

INSERT INTO NOODLE VALUES (
 1, '안성탕면', '농심', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 1, '김치라면', '삼양', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 1, '진라면', '오뚜기', 'C', 800, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 1, '꼬꼬면', '팔도', 'C', 1000, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 2, '신라면', '농심', 'C', 1100, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 2, '삼양라면', '삼양', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 3, '너구리', '농심', 'M', 850, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 3, '나가사키짬뽕', '삼양', 'C', 1300, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 4, '짜파게티', '농심', 'C', 1200, NOW() + INTERVAL 3 MONTH);

SELECT * FROM NOODLE;

-- 1번
SELECT COMPANY, COUNT(*) "C OUN T" FROM NOODLE GROUP BY COMPANY;

-- 2번
SELECT COMPANY, CONCAT(COUNT(*),'개') FROM NOODLE GROUP BY COMPANY ORDER BY COUNT(*) ASC;

-- 3번
SELECT COMPANY, COUNT(*) FROM NOODLE GROUP BY COMPANY HAVING COUNT(*) >= 3;
SELECT * FROM NOODLE;
-- 4번
SELECT name, COMPANY, date_format(E_DATE, '%Y년 %m월 %d일') AS E_DATE FROM NOODLE WHERE PRICE >= 800 AND KIND = 'M';

-- 5번
SELECT CONCAT(MAX(PRICE),'원') AS PRICE FROM NOODLE;

-- 6번
SELECT COMPANY, CONCAT(MIN(PRICE),'원') AS PRICE FROM NOODLE GROUP BY COMPANY;

-- 7번
SELECT COMPANY, CONVERT(CONCAT(SUM(PRICE),'원') USING UTF8) AS '제조사별 합계' FROM NOODLE GROUP BY COMPANY order by SUM(PRICE) ASC;
-- SELECT COMPANY, CAST(CONCAT(SUM(PRICE),'원') AS VARCHAR(30)) AS '제조사별 합계' FROM NOODLE GROUP BY COMPANY order by SUM(PRICE) ASC;

-- 8번
SELECT COMPANY, CONCAT(ROUND(AVG(PRICE),0),'원') AS '제조사별 평균' FROM NOODLE GROUP BY COMPANY ORDER BY AVG(PRICE) DESC;



